# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rotation_matrix <- function(n) {
    .Call(`_BATTS_rotation_matrix`, n)
}

run_adaboost <- function(X, group_labels, num_trees, max_resol, learn_rate, L_candidates, alpha_cutpoint, labels_train, n_min_obs_per_node, n_ratio_per_node, use_gradient, size_burnin, size_backfitting, thin, prob_moves, lambda_0, a_prior_lambda, b_prior_lambda, a_prior_omega, b_prior_omega, update_lambda, alpha_tree, beta_tree, output_BART_ensembles, quiet) {
    .Call(`_BATTS_run_adaboost`, X, group_labels, num_trees, max_resol, learn_rate, L_candidates, alpha_cutpoint, labels_train, n_min_obs_per_node, n_ratio_per_node, use_gradient, size_burnin, size_backfitting, thin, prob_moves, lambda_0, a_prior_lambda, b_prior_lambda, a_prior_omega, b_prior_omega, update_lambda, alpha_tree, beta_tree, output_BART_ensembles, quiet)
}

evaluate_balance_weight_boosting <- function(tree_list, eval_points) {
    .Call(`_BATTS_evaluate_balance_weight_boosting`, tree_list, eval_points)
}

evaluate_balance_weight_BART <- function(forest_list, eval_points) {
    .Call(`_BATTS_evaluate_balance_weight_BART`, forest_list, eval_points)
}

